name: Deployment Pipeline 


# este pipeline se va a ejecutar cuando hagamos un push a master o develop
# y cuando hagamos un pull_request a master o develop
on: 
  push:
    branches: [master,Develop]
  pull_request:
    branches: [master,Develop]
    types: [opened]

jobs: 
  deploy:
    runs-on: ubuntu-18.04
    steps:
      # con este paso vamos a traer la ultima version del master
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # tenemos que instalar las dependencias
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      # instalamos las dependiencias de node.
      - name: Install dependencies
        run: npm install
      - name: npm Init
        run: npm init -y
      # buildeamos
      - name: Build
        run: npm run build --if-present
      # corremos los tests
      - name: Test
        run: npm run test
