name: Deployment Pipeline 


# este pipeline se va a ejecutar cuando hagamos un push a master
# y cuando hagamos un pull_request a master
on: 
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
    types: [opened]

jobs: 
  deploy:
    runs-on: ubuntu-18.04
    steps:
      # con este paso vamos a traer la ultima version del master
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # tenemos que instalar las dependencias
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      # instalamos las dependiencias de node.
      - name: Install dependencies
        run: npm install
      - name: npm Init
        run: npm init -y
      # buildeamos
      - name: Build
        run: npm run build --if-present
      # aca correriamos los test, segun el video los pone despues
      # del build pero me hace ruido
      # - name: Test
      #   run: npm run test
